### PR TITLE
Make DigiNode Tools slightly more prominent

### PR DESCRIPTION
**Pull request by saltedlolly**
Sorry I made a couple more tweaks. 

Given how much time I have spent working on DigiNode Tools, I hope noone objects to me making it slightly more prominent on the digibyte.org website:
- Bumped DigiNode Tools to the front of the "Tools & Solutions" section so it is visible on the page at load time. (no need to click right)
- Updated English description (I have not translated this but the DigiNode site is currently only in English. For other languages the original description is fine.)

If it encourages more people to run a node then great.

### CODE REVIEW

**Comment by saltedlolly** [comment]
Screenshot 2024-03-29 at 5 36 02 pm

**Review by DGBNOOB — APPROVED** [review]
Olly, this is my first review. I agree with your reasoning for wanting to bump DigiNode Tool to the front for more exposure. Personally, I think that's a great idea since the Tool lowers the barrier for community members to support the network. For the commits and files changed, I can see the changes in the lines added where DigiNode Tool is in front of GetBlock and nownodes. I don't know enough to be able to catch any mistakes if any were made or how to test the changes, however, I will give the PR a cACK.

**Comment by Sbosvk** [comment]
I don't necessarily disagree with this change, but I think there may have been a misunderstanding of how these sections are intended to be viewed. There is no priority implied, simply an order of addition. I think we need to consider what kind of statement that his change makes towards creators of other solutions that have also put a lot of time, money and effort into providing an application-level entry point to decentralized applications using DigiByte.

I can't help but question the motive for this, and whether we really want to start prioritizing community solutions.

**Comment by saltedlolly** [comment]
My reason for moving it to the left is pretty self explanatory - it is simply to make it more visible on the page. As it stands now you have to click the right arrow to know it even exists. I was concerned that it will rarely be discovered in its current position. Moving it also makes it clear that not everything in that section is a node api provider. The whole point of DigiNode Tools is to get more people to run a node. That's less likely if they can't find it. I obviously don't want to obscure other projects but there are only two slots visible by default. Perhaps you have a better solution?

**Comment by Sbosvk** [comment]
I understand the reason and the functionality of the sliders, that's not in question. I don't have a solution, and I don't personally see anything to solve. Even if we were to for example expand the amount of items that are visible in the first pagination, there will almost always be items that are not immediately visible, that is just the limitation of the layout.
I don't mean to say you are trying to obscure anything, my concern is simply whether we with the website want to play favouritism, which in my opinion is what we would be implying with this change.

The objective way would be to simply leave items in order of addition as we always have (not counting the ecosystem quick picks). Perhaps I am overthinking it.

**Review by JaredTate — APPROVED** [review]
cACK. Thanks for all your work on DigiNode Tools.

**Comment by DGBNOOB** [comment]
> I understand the reason, and the functionality of the sliders, that's not in question. I don't have a solution, and I don't personally see anything to solve. Even if we were to for example expand the amount of items that are visible in the first pagination, there will almost always be items that are not immediately visible, that is just the limitation of the layout. I don't mean to say you are trying to obscure anything, my concern is simply whether we with the website want to play favouritism, which in my opinion is what we would be implying with this change.
> 
> The objective way would be to simply leave items in order of addition as we always have (not counting the ecosystem quick picks). Perhaps I am overthinking it.

I appreciate your point of view on giving preference to community projects, I did not consider the message we'd be sending to all wanting to add to the website and then expecting to have there item bumped for more exposure. I will keep this as a lesson learned and use this example for future cases. 

After thinking about this situation, I think there needs to be room left for judgement and special circumstances. About a year ago a node service provider offered free API services for a limited time as a promotion and then thought about, what happens at the end of the promotion? Would it cause a sudden drop in nodes? The DigiNode Tools lowers the barrier for community member to support the network-organically. Both community nodes and node service providers are needed, however, what would happen if a node service provider went out of business, delisted DigiByte, or was attacked resulting in the services going down. These are worst case scenarios, which IMO gives validity to putting DigiNode Tools in a more visible location.

**Review by ycagel — APPROVED** [review]
cACK

**Pull request merged**
