### PR TITLE
feat: update X logo (formerly twitter)

### PR DESCRIPTION
**Pull request by DennisPitallano**
issue #131

used https://fontawesome.com/icons/x-twitter?f=brands&s=solid  icon version
x-twitter-brands-solid

**you can review the revision preview** here: https://dg-bio.vercel.app/en-us/

### CODE REVIEW

**Comment by DGBNOOB** [comment]
Dennis, awesome job as always. The https://dg-bio.vercel.app/en-us/ helped out with the visual aspect. I did notice the <link> tag in the HTML document to include Font Awesome icons was missing for the RO file. dg-bio.vercel.app made it easier to spot. I think everything else looks excellent. Once that's fixed, I'm going to give it a passing review.

https://github.com/user-attachments/assets/70307555-36f1-4d23-a8f3-09d12f82d340

**Comment by DGBNOOB** [comment]
Dennis, awesome job as always. The https://dg-bio.vercel.app/en-us/ helped out with the visual aspect. I did notice the <link> tag in the HTML document to include Font Awesome icons was missing for the RO file. dg-bio.vercel.app made it easier to spot. I think everything else looks excellent. Once that's fixed, I'm going to give it a passing review.

https://github.com/user-attachments/assets/70307555-36f1-4d23-a8f3-09d12f82d340

**Comment by DennisPitallano** [comment]
> Dennis, awesome job as always. The https://dg-bio.vercel.app/en-us/ helped out with the visual aspect. I did notice the tag in the HTML document to include Font Awesome icons was missing for the RO file. dg-bio.vercel.app made it easier to spot. I think everything else looks excellent. Once that's fixed, I'm going to give it a passing review.
> 
>  Screen.Recording.2024-12-10.135136.mp4

Great catch, Jose @DGBNOOB ! 🐞

I’ve made the update, it should be good now.

**Comment by DGBNOOB** [comment]
I might of missed it the first time, there are two X x in "Meet the creator of DigiByte".

Not 100% sure but i think the extra x is here. Still a great job. This fix should wrap it up unless you find more twitter's that need to be converted to X's. 

X   x

X x

**Comment by DennisPitallano** [comment]
> I might of missed it the first time, there are two X x in "Meet the creator of DigiByte".
> 
> Not 100% sure but i think the extra x is here. Still a great job. This fix should wrap it up unless you find more twitter's that need to be converted to X's.
> 
> X x
> 
> X x

Yeah, that was me. The extra 'X' character shouldn’t be there. 🫠
Let's try again, I've updated it and removed the extra X's.

**Review by DGBNOOB — APPROVED** [review]
Update X logo Pull Request 132 to address issue 131
X-Twitter Icon was obtained from Font Awesome website
The revisions preview through  https://dg-bio.vercel.app/en-us/ made it easy to view the changes as a preview page. Most of the icons were updated at the top of the website, in the community section and in the footer.

.hintrc file was added
Added <link> tag in an HTML document to include Font Awesome icons

I used split view to compare the changes and here are what they were before to what they are now:

1.	Changed from: "https://twitter.com/jaredctate/status/1190673943876841475" target=" to "https://x.com/jaredctate/status/1190673943876841475" target="_blank"

2.	Changed from <a class="rightpad20" href="https://twitter.com/DigiByteCoin" target="_blank"><i class="fab fa-twitter-square zoom" to https://x.com/DigiByteCoin" target="_blank"><i class="fa-brands fa-x-twitter zoom"

3.	Changed from "https://twitter.com/digibytecoin/status/982696268928618496" to "https://x.com/digibytecoin/status/982696268928618496" target="

4.	Changed from "https://twitter.com/jaredctate/status/1217178454229225473" to "https://x.com/jaredctate/status/1217178454229225473" target="

5.	Changed from https://twitter.com/jaredctate" target="_blank"><i class="fab fa-twitter"></i> Twitter to "https://x.com/jaredctate" target="_blank"><i class="fa-brands fa-x-twitter"></i> 

6.	Changed from "https://twitter.com/DigiByteCoin" target="_blank"><i class="fab fa-twitter" aria-hidden="true" to "fa-brands fa-x-twitter"

css/base.css Added @import "font-awesome/css/all.min.css"

Langmenu/ticker.html-"https://twitter.com/DigiByteCoin" rel="noopener" title="twitter" target="_blank"><i class="fab to "https://x.com/DigiByteCoin" rel="noopener" title="X" target="_blank"><i class="fa-brands fa-x-twitter"

Excellent job Dennis, thank you for doing this. 
Recommend approval cACK.

**Review by ycagel — APPROVED** [review]
cACK. Thanks @DennisPitallano!

**Pull request merged**
