### PR TITLE
fix: issue #105

### PR DESCRIPTION
**Pull request by DennisPitallano**
#105
Add DigiByte Domains.

### CODE REVIEW

**Review by DGBNOOB — APPROVED** [review]
Awesome job @DennisPitallano, 
The DigiByte Domains description index.html which in English and the 34 translated language versions, testimonial name & link, and DigiByte Domain name png in the images/avatars folder. Did not test, however, recommend for approval. 
cACK

**Review by JaredTate — APPROVED** [review]
cACK. Thanks for doing this!

**Review by ycagel — APPROVED** [review]
cACK. Appreciate the work @DennisPitallano!

**Comment by saltedlolly** [comment]
Nice work @DennisPitallano 

Appreciate all the work you are doing on the digibyte.org website. :)

**Pull request merged**
