### PR TITLE
Enable PWA

### PR DESCRIPTION
**Pull request by DennisPitallano**
#100
Enable PWA

### CODE REVIEW

**Comment by Sbosvk** [comment]
Interesting PR. I wasn't aware we were in need of PWA, although I do see how it could increase performance assuming it is not only used when offline.

@DennisPitallano can you please provide some background as to what is the reason for suggesting this PR?

**Comment by DennisPitallano** [comment]
> Interesting PR. I wasn't aware we were in need of PWA, although I do see how it could increase performance assuming it is not only used when offline.
> 
> @DennisPitallano can you please provide some background as to what is the reason for suggesting this PR?

The main reason for this is to give users a better experience. When a website has app-like features, people tend to be more satisfied. And once they've installed it on their device, they don't have to bother with opening a browser and typing in the URL. Just like any other app, they can just tap or click the icon to get right to the website.
I hope this makes sense 😊

**Review by DGBNOOB — COMMENTED** [review]
Dennis, I didn't know what PWA's were until I seen this PR created. You do a good job of illustrating how the PWA works. Looking at this feature from a consumers perspective, people like convenience, however, I'm not sure how many people would want to go through the extra steps to add the PWA. User experience is important, I'm going to do a little more research on PWA's to learn more about the pro's/cons and if there are know issues for my own understanding.

**Comment by DennisPitallano** [comment]
> Dennis, I didn't know what PWA's were until I seen this PR created. You do a good job of illustrating how the PWA works. Looking at this feature from a consumers perspective, people like convenience, however, I'm not sure how many people would want to go through the extra steps to add the PWA. User experience is important, I'm going to do a little more research on PWA's to learn more about the pro's/cons and if there are know issues for my own understanding.

Yeah, I get it. Some folks might not know what PWA is because they're used to just browsing websites the usual way. And yeah, not all websites have that PWA magic enabled yet.😊

Here are a few websites that have PWA functionality enabled.
image
image
image
image

**Review by JaredTate — APPROVED** [review]
cACK. Very cool, I did not even know what a PWA was until this PR. Thanks for adding the functionality to do this.

**Review by ycagel — APPROVED** [review]
cACK

**Pull request merged**
